import { useState } from 'react'
import { Bot, Clipboard, RefreshCw, Send, Sparkles, Trash2, User } from 'lucide-react'
import { Button, Panel, SectionHeading } from '../components/ui'
import { useApp } from '../context/AppContext'

const suggestions = ['Which students need immediate attention?', 'Which department has the highest risk?', 'Recommend interventions for high-risk students.', 'Generate a department report.']
function answer(prompt, students) { const high = students.filter((student) => student.risk >= 75); if (/department/i.test(prompt)) return `The current highest-risk signal is concentrated in CSE and ECE. ${high.length} students are above the high-risk threshold, with attendance and recent academic decline as the strongest shared drivers.`; if (/intervention/i.test(prompt)) return `I recommend academic counselling for ${high[0]?.name || 'the highest-risk cohort'}, attendance monitoring for the next two weeks, and a weekly mentor check-in. These actions should be reviewed by a human mentor.`; return `Today’s priority queue includes ${high.map((student) => `${student.name} (${student.risk} risk)`).join(', ')}. The clearest shared reasons are attendance below 75%, incomplete assignments, and declining engagement.` }
export default function Copilot() { const { students, notify } = useApp(); const [messages, setMessages] = useState([{ role: 'assistant', text: 'I’m connected to the EduPulse demo workspace. Ask me about risk, students, departments, or interventions.' }]); const [input, setInput] = useState(''); const [loading, setLoading] = useState(false); const [analysisStage, setAnalysisStage] = useState(0); const [lastPrompt, setLastPrompt] = useState('')
  const send = (prompt = input) => { if (!prompt.trim() || loading) return; setInput(''); setLastPrompt(prompt); setMessages((current) => [...current, { role: 'user', text: prompt }]); setLoading(true); setAnalysisStage(1); setTimeout(() => setAnalysisStage(2), 260); setTimeout(() => setAnalysisStage(3), 520); setTimeout(() => { setMessages((current) => [...current, { role: 'assistant', text: answer(prompt, students) }]); setLoading(false); setAnalysisStage(0) }, 760) }
  return <div><SectionHeading eyebrow="AI / decision support" title="AI copilot" copy="Ask questions in plain language. Responses use the current demo workspace and are clearly framed as decision support." action={<Button variant="secondary" icon={<Trash2 size={15} />} onClick={() => setMessages([])}>Clear chat</Button>} /><div className="copilot-layout"><Panel className="chat-panel"><div className="chat-messages">{messages.map((message, index) => <div className={`chat-message chat-${message.role}`} key={`${message.role}-${index}`}><div className="chat-avatar">{message.role === 'assistant' ? <Bot size={15} /> : <User size={15} />}</div><div className="chat-bubble"><p>{message.text}</p>{message.role === 'assistant' && <div className="message-actions"><button onClick={() => { navigator.clipboard?.writeText(message.text); notify('Copied to clipboard.', 'info') }}><Clipboard size={13} /> Copy</button><button onClick={() => send(lastPrompt)}><RefreshCw size={13} /> Regenerate</button></div>}</div></div>)}{loading && <div className="chat-message chat-assistant"><div className="chat-avatar"><Bot size={15} /></div><div className="chat-bubble ai-thinking"><strong>AI ANALYZING</strong><span className={analysisStage >= 1 ? 'stage-done' : ''}>Analyzing institutional data</span><span className={analysisStage >= 2 ? 'stage-done' : ''}>Analyzing risk patterns</span><span className={analysisStage >= 3 ? 'stage-done' : ''}>Generating recommendation</span></div></div>}</div><form className="chat-input" onSubmit={(event) => { event.preventDefault(); send() }}><input value={input} onChange={(event) => setInput(event.target.value)} placeholder="Ask about your student success data..." /><button type="submit" disabled={loading || !input.trim()} aria-label="Send message"><Send size={17} /></button></form></Panel><Panel className="suggestion-panel" eyebrow="Try asking" title="Suggested prompts"><div className="suggestions">{suggestions.map((suggestion) => <button key={suggestion} onClick={() => send(suggestion)}><Sparkles size={14} />{suggestion}</button>)}</div></Panel></div></div>
}
