import { useState } from 'react'
import { Eye, EyeOff, LockKeyhole, Mail, ShieldCheck } from 'lucide-react'
import { Link, useLocation, useNavigate, useSearchParams } from 'react-router-dom'
import { Button, Panel } from '../components/ui'
import { useAuth } from '../context/AuthContext'
import { demoAccounts } from '../services/authService'

export default function Login() {
  const navigate = useNavigate(); const location = useLocation(); const [params] = useSearchParams(); const { login, loading, setAuthMessage } = useAuth(); const [email, setEmail] = useState('admin@edupulse.demo'); const [password, setPassword] = useState('EduPulse2025!'); const [showPassword, setShowPassword] = useState(false); const [remember, setRemember] = useState(true); const [error, setError] = useState('')
  const submit = async (event) => { event.preventDefault(); setError(''); if (!email.trim()) return setError('Please enter your email.'); if (!email.includes('@')) return setError('Please enter a valid email address.'); if (!password) return setError('Password is required.'); if (password.length < 8) return setError('Password must contain at least 8 characters.'); try { const result = await login(email, password); if (!remember) sessionStorage.setItem('edupulse-session-only', 'true'); setAuthMessage(`Welcome back, ${result.user.firstName}.`); navigate(params.get('returnTo') || location.state?.from?.pathname || '/dashboard', { replace: true }) } catch (loginError) { setError(loginError.message === 'INVALID_CREDENTIALS' ? 'Invalid email or password.' : 'Unable to sign in right now. Please try again.') } }
  const chooseDemo = (account) => { setEmail(account.email); setPassword(account.password); setError('') }
  return <main className="auth-page"><div className="login-brand"><div className="brand-mark"><span /><span /><span /></div><strong>Veyra</strong><small>Student Intelligence Platform</small></div><Panel className="login-panel"><p className="eyebrow">Secure workspace access</p><h1>Welcome back</h1><p>Sign in to continue to your student success command center.</p><form className="auth-form" onSubmit={submit}><label><span>Email</span><div className="auth-input"><Mail size={15} /><input type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="you@university.edu" /></div></label><label><span>Password</span><div className="auth-input"><LockKeyhole size={15} /><input type={showPassword ? 'text' : 'password'} value={password} onChange={(event) => setPassword(event.target.value)} /><button type="button" onClick={() => setShowPassword(!showPassword)} aria-label={showPassword ? 'Hide password' : 'Show password'}>{showPassword ? <EyeOff size={15} /> : <Eye size={15} />}</button></div></label>{error && <div className="form-error">{error}</div>}<div className="auth-options"><label><input type="checkbox" checked={remember} onChange={(event) => setRemember(event.target.checked)} /> Remember me</label><Link to="/forgot-password">Forgot password?</Link></div><Button type="submit" disabled={loading} icon={<ShieldCheck size={15} />}>{loading ? 'Signing in...' : 'Sign in'}</Button></form><div className="demo-access"><span>Demo access · password: <strong>EduPulse2025!</strong></span><div>{demoAccounts().map((account) => <button key={account.email} onClick={() => chooseDemo(account)}>{account.role}</button>)}</div></div></Panel></main>
}