import { useEffect, useState } from 'react'
import { RotateCcw, Sparkles, Target } from 'lucide-react'
import { Button, Panel, ProgressBar, SectionHeading } from '../components/ui'
import { useApp } from '../context/AppContext'

const fields = [['attendance', 'Attendance', '%', 0, 100], ['studyHours', 'Study hours', 'h/day', 0, 8], ['assignments', 'Assignment completion', '%', 0, 100], ['quiz', 'Quiz average', '%', 0, 100], ['engagement', 'Engagement', '%', 0, 100], ['participation', 'Participation', '%', 0, 100]]
export default function Simulator() {
  const { students, notify } = useApp(); const student = students[0]; const [values, setValues] = useState({ ...student, participation: student.engagement }); const [result, setResult] = useState(null); const [timer, setTimer] = useState(null)
  const calculate = (nextValues) => { const improvement = Math.round(((nextValues.attendance - student.attendance) * .35 + (nextValues.assignments - student.assignments) * .2 + (nextValues.engagement - student.engagement) * .2 + (nextValues.quiz - student.quiz) * .15 + (nextValues.participation - student.engagement) * .1) / 2); const simulated = Math.max(5, Math.min(98, student.success + improvement)); const feature = nextValues.attendance - student.attendance >= Math.max(nextValues.assignments - student.assignments, nextValues.engagement - student.engagement) ? 'Attendance' : 'Assignment completion'; setResult({ original: student.success, simulated, difference: simulated - student.success, feature }) }
  const change = (field, value) => { const next = { ...values, [field]: Number(value) }; setValues(next); clearTimeout(timer); setTimer(setTimeout(() => calculate(next), 350)) }
  useEffect(() => () => clearTimeout(timer), [timer])
  return <div><SectionHeading eyebrow="Intelligence / scenario planning" title="Student success simulator" copy="Explore modeled changes without modifying the student's actual record. Every result is an estimate for planning, not a guarantee." /><div className="simulator-layout"><Panel eyebrow="Scenario inputs" title="Adjust the levers"><div className="slider-list">{fields.map(([field, label, unit, min, max]) => <label className="slider-field" key={field}><span><strong>{label}</strong><b>{values[field]} {unit}</b></span><input type="range" min={min} max={max} step={field === 'studyHours' ? .5 : 1} value={values[field]} onChange={(event) => change(field, event.target.value)} /><ProgressBar value={(values[field] / max) * 100} tone={field === 'attendance' ? 'cyan' : 'green'} /></label>)}</div><div className="modal-actions"><Button variant="secondary" icon={<RotateCcw size={15} />} onClick={() => { setValues({ ...student, participation: student.engagement }); setResult(null); notify('Simulation reset to current student values.', 'info') }}>Reset</Button><Button icon={<Target size={15} />} onClick={() => notify('Scenario saved as an intervention planning note.', 'info')}>Apply scenario</Button></div></Panel><Panel className="simulation-result" eyebrow="Modeled outcome" title="What could change?"><div className="probability-compare"><div><span>Current estimate</span><strong>{result?.original ?? student.success}%</strong></div><div className="compare-arrow">→</div><div><span>Simulated estimate</span><strong className="simulation-value">{result?.simulated ?? student.success}%</strong></div></div>{result ? <><div className="change-pill">{result.difference >= 0 ? '+' : ''}{result.difference}% change</div><div className="impact-callout"><Sparkles size={18} /><span><strong>Most impactful improvement</strong><br />{result.feature} is showing the highest modeled impact in this scenario.</span></div></> : <div className="simulation-empty"><Sparkles size={22} /><p>Move a slider to calculate a scenario.</p></div>}<small className="disclaimer">Simulation only — not a guaranteed outcome. Model outputs support human decision-making.</small></Panel></div></div>
}
